### PR TITLE
Support SeekableByteChannel#position for reads.

### PR DESCRIPTION
**Pull request by tomwhite**
[Review on Reviewable](https://reviewable.io/reviews/damiencarol/jsr203-hadoop/13)

### CODE REVIEW

**Comment by damiencarol** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/damiencarol/jsr203-hadoop/13)

**Comment by damiencarol** [comment]
@tomwhite Thanks for this little patch. Sorry for the delay.

**Comment by tomwhite** [comment]
@damiencarol No problem - thanks for merging it!

**Comment by damiencarol** [comment]
@tomwhite you're welcome. I will release a maven artifcat. Are you interested?

**Comment by tomwhite** [comment]
@damiencarol yes, that would be great!

**Comment by tomwhite** [comment]
@damiencarol did you ever release the artifact for this? Thanks.

**Comment by damiencarol** [comment]
WIP

**Comment by damiencarol** [comment]
A maven artifact was deployer on public repo:
https://github.com/damiencarol/jsr203-hadoop/issues/15

**Pull request merged**
